name: 'Generate release notes'
description: 'action to generate release notes'
inputs:
  token:  
    description: 'Github token'
    required: true
    # try making source repo a variable
  # source-repo:
  #   description: 'Source repository'
  #   required: true
  docs-repo:
    description: 'Docs repository'
    required: true
  base-branch:
    description: 'branch to create PR against'
    required: true
  allow-automerge:
    type: boolean
    default: false
  release-notes-path:
    description: 'path to release notes file (including file name)'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: ${{github.repository}}
        fetch-depth: 0
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: ${{inputs.docs-repo}}
        ref: ${{inputs.base-branch}}
        token: ${{inputs.token}}
        repository: ${{inputs.docs-repo}}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # install the python version needed
    - name: run script
      run: |
        pip install GitPython
        # create file if it does not exist. Parent folder must exist!
        if [ ! -f ${{inputs.docs-repo}}/${{inputs.release-notes-path}} ]; then
          echo "release-notes file does not exist. Creating empty file now..."
          touch ${{inputs.docs-repo}}/${{inputs.release-notes-path}}
        fi
        echo "copying release notes file to source repo and running script"
        # copy release notes file and create_release_notes.py to source repo and run it
        cp ${{inputs.docs-repo}}/${{inputs.release-notes-path}} ${{github.repository}}/release-notes-tmp.md
        cp ${{ github.action_path }}/create_release_notes.py ${{github.repository}}/create_release_notes.py
        cd ${{github.repository}}
        # check if python script ran successfully
        python create_release_notes.py --source ${{github.repository}}
        # copy release notes file back to docs repo
        echo "copying release notes file back to docs repo and creating PR"
        cp release-notes-tmp.md ../../${{inputs.docs-repo}}/${{inputs.release-notes-path}}
        echo "github.repository: ${{github.repository}}"
      shell: bash
    - name: create PR
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{inputs.token}}
        path: ${{inputs.docs-repo}}
        commit-message: 'generated release note'
        branch: new-release-notes/preview
        title: '[Auto PR] Generated release notes'
        delete-branch: true
        base: ${{inputs.base-branch}}
    # - name: automatic merge
    #   if: ${{inputs.allow-automerge == 'true'}}
    #   env:
    #     GH_TOKEN: ${{inputs.token}}
    #   run: |
    #     gh pr merge new-release-notes/preview --auto --delete-branch --rebase --repo ${{inputs.docs-repo}}
    #   shell: bash
