name: Unit tests
on:
  push:
    branches:
      - unittest

jobs:
  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest   
    steps:
      - name: setup Python
        uses: actions/setup-python@v4
      - name: Run unit tests
        run: |
          ls
          python -m unittest